export const DOCUMENT_TYPES = {

  AADHAAR: "AADHAAR",

  PAN: "PAN",

  RATION_CARD: "RATION_CARD",

  INCOME_CERTIFICATE: "INCOME_CERTIFICATE",

  CASTE_CERTIFICATE: "CASTE_CERTIFICATE",

  DOMICILE_CERTIFICATE: "DOMICILE_CERTIFICATE",

  RESIDENCE_CERTIFICATE: "RESIDENCE_CERTIFICATE",

  DISABILITY_CERTIFICATE: "DISABILITY_CERTIFICATE",

  BANK_PASSBOOK: "BANK_PASSBOOK",

  PASSPORT: "PASSPORT",

  VOTER_ID: "VOTER_ID",

  DRIVING_LICENSE: "DRIVING_LICENSE",

  BPL_CARD: "BPL_CARD",

  BIRTH_CERTIFICATE: "BIRTH_CERTIFICATE",

  DEATH_CERTIFICATE: "DEATH_CERTIFICATE",

};